"""Regression test for the reverse-engineered task recipe.

Task dirs are generated, not committed, so this is what stands in for them:
rebuilding the whole dataset from ``provenance/tasks.jsonl`` must reproduce the
``gold.txt`` / ``pool_ncts.txt`` bytes the index records hashes for. For the 9
tasks that shipped upstream — whose gold is Microsoft's hand audit, not ours —
that is the whole evidence that ``build_tasks.py`` implements upstream's
construction —

    pool == every judged grade-0 + every judged grade-1 + gold

— and not something that merely looks similar. For the tasks we generated it is
the check that the recipe still emits what the index was exported from. If this
test goes red, every generated task is suspect.

``trial_ncts.txt`` is only checked as a *set*: it is the bootstrap's download
list and is deliberately shuffled.

Needs ``qrels2021.txt`` / ``qrels2022.txt``, downloaded once into
``assets/clinical_trial_matching/assets/`` and reused. Skips (rather than fails)
if TREC is unreachable and nothing is cached.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from urllib.error import URLError

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = REPO_ROOT / "scripts" / "trec_ct"
INDEX_FILE = REPO_ROOT / "provenance" / "tasks.jsonl"

sys.path.insert(0, str(SCRIPTS))

import build_tasks  # noqa: E402
import trec_data as td  # noqa: E402


def _read(path: Path) -> list[str]:
    return [line.strip() for line in path.read_text().splitlines() if line.strip()]


# The 9 tasks that shipped upstream, whose gold is Microsoft's hand audit rather
# than ours. They are the provenance anchor for the whole recipe: everything else
# in the index was produced by build_tasks.py from our own audit, so if these
# ever stop round-tripping we have lost the only independent check on it.
UPSTREAM_TOPICS = (6, 8, 19, 26, 27, 29, 35, 45, 75)

INDEX = build_tasks.load_index(INDEX_FILE)


@pytest.fixture(scope="module")
def regenerated(tmp_path_factory) -> Path:
    """Rebuild the entire dataset from the committed index, once."""
    target = tmp_path_factory.mktemp("roundtrip")
    try:
        build_tasks.main(["--index", str(INDEX_FILE), "--out", str(target)])
    except (URLError, OSError) as exc:  # pragma: no cover - offline CI
        pytest.skip(f"TREC qrels unavailable: {exc!r}")
    return target


def _ids(row: dict) -> str:
    return row["task_id"]


def test_the_index_covers_the_whole_dataset():
    assert len(INDEX) == 110
    assert {row["year"] for row in INDEX} == {2021, 2022}
    assert len({row["task_id"] for row in INDEX}) == len(INDEX)


def test_the_upstream_tasks_are_all_still_present():
    committed = {row["topic_id"] for row in INDEX if row["year"] == 2021}
    assert set(UPSTREAM_TOPICS) <= committed


@pytest.mark.parametrize("row", INDEX, ids=_ids)
def test_gold_source_marker_matches_the_upstream_set(row: dict):
    """Task name doesn't say who audited the gold — ``gold_source`` does."""
    is_upstream = row["year"] == 2021 and row["topic_id"] in UPSTREAM_TOPICS
    if is_upstream:
        assert row["gold_source"] == build_tasks.UPSTREAM_GOLD_SOURCE
    else:
        assert row["gold_source"].startswith("llm-audit:"), row["gold_source"]


@pytest.mark.parametrize("row", INDEX, ids=_ids)
def test_pool_and_gold_roundtrip(row: dict, regenerated: Path):
    """The index's hashes are the committed stand-in for the generated bytes."""
    rebuilt = regenerated / row["task_id"]
    assert rebuilt.is_dir(), f"{row['task_id']} was not regenerated"

    gold_file = rebuilt / "tests" / "gold.txt"
    pool_file = rebuilt / "tests" / "pool_ncts.txt"
    assert hashlib.sha256(gold_file.read_bytes()).hexdigest() == row["gold_sha256"]
    assert hashlib.sha256(pool_file.read_bytes()).hexdigest() == row["pool_sha256"]
    assert _read(gold_file) == sorted(row["gold"])
    assert len(_read(pool_file)) == row["n_pool"]

    # The bootstrap downloads exactly the pool; the shuffle is presentation only.
    trials = _read(rebuilt / "environment" / "workspace" / "trial_ncts.txt")
    assert set(trials) == set(_read(pool_file))
    # And the marker survives regeneration — relabelling upstream's 9 as ours
    # would be silent and permanent.
    assert build_tasks.existing_gold_source(rebuilt) == row["gold_source"]


@pytest.mark.parametrize("row", INDEX, ids=_ids)
def test_pool_holds_no_unaudited_grade_2(row: dict, regenerated: Path):
    """The invariant that makes recall@top50 == 1.0 reachable at all."""
    try:
        qrels = td.load_qrels(td.get_year(row["year"]))
    except (URLError, OSError) as exc:  # pragma: no cover - offline CI
        pytest.skip(f"TREC qrels unavailable: {exc!r}")

    rebuilt = regenerated / row["task_id"]
    gold = set(_read(rebuilt / "tests" / "gold.txt"))
    pool = set(_read(rebuilt / "tests" / "pool_ncts.txt"))
    judged = qrels[row["topic_id"]]

    hidden = {nct for nct in pool - gold if judged.get(nct) == td.GRADE_ELIGIBLE}
    assert not hidden, f"topic {row['topic_id']}: hidden positives in pool: {sorted(hidden)}"
    assert gold <= pool
    assert all(judged.get(nct) == td.GRADE_ELIGIBLE for nct in gold)


def _write_jsonl(path: Path, rows: list[dict]) -> Path:
    path.write_text("\n".join(json.dumps(r) for r in rows) + "\n")
    return path


def test_load_audit_ignores_other_years(tmp_path: Path):
    """Topic numbers restart every track, so gold must be keyed on (year, topic)."""
    audit = _write_jsonl(
        tmp_path / "mixed.jsonl",
        [
            {"year": 2021, "topic_id": 12, "nct_id": "NCT00000001", "clean_eligible": True},
            {"year": 2022, "topic_id": 12, "nct_id": "NCT00000002", "clean_eligible": True},
            {"year": 2022, "topic_id": 12, "nct_id": "NCT00000003", "clean_eligible": False},
        ],
    )
    assert build_tasks.load_audit(audit, td.get_year(2022)) == {12: ["NCT00000002"]}
    assert build_tasks.load_audit(audit, td.get_year(2021)) == {12: ["NCT00000001"]}
    # An audit for a year we aren't building yields nothing rather than mis-keyed gold.
    assert build_tasks.load_audit(audit, td.get_year(2023)) == {}


def test_index_gold_is_keyed_on_year_too(tmp_path: Path):
    """Same hazard as the audit, on the path that now builds the whole dataset."""
    rows = [
        {
            "year": 2021,
            "topic_id": 12,
            "task_id": "clinical_trial_matching_task_12",
            "gold_source": "microsoft-hand-audit",
            "gold": ["NCT00000001"],
        },
        {
            "year": 2022,
            "topic_id": 12,
            "task_id": "clinical_trial_matching_2022_task_12",
            "gold_source": "llm-audit:claude-sonnet-5",
            "gold": ["NCT00000002"],
        },
    ]
    gold, source = build_tasks.index_gold(rows, td.get_year(2022))
    assert gold == {12: ["NCT00000002"]}
    assert source == {12: "llm-audit:claude-sonnet-5"}
    gold, source = build_tasks.index_gold(rows, td.get_year(2021))
    assert gold == {12: ["NCT00000001"]}
    assert source == {12: "microsoft-hand-audit"}


def test_build_rejects_gold_that_is_not_grade_2_for_the_year(tmp_path: Path):
    """The guard that catches a gold source built against a different year."""
    try:
        qrels = td.load_qrels(td.get_year(2021))
    except (URLError, OSError) as exc:  # pragma: no cover - offline CI
        pytest.skip(f"TREC qrels unavailable: {exc!r}")

    not_eligible = sorted(
        nct for nct, grade in qrels[19].items() if grade != td.GRADE_ELIGIBLE
    )[:4]
    audit = _write_jsonl(
        tmp_path / "wrong.jsonl",
        [
            {"year": 2021, "topic_id": 19, "nct_id": nct, "clean_eligible": True}
            for nct in not_eligible
        ],
    )
    with pytest.raises(SystemExit, match="not.*grade-2"):
        build_tasks.main(
            ["--year", "2021", "--audit", str(audit), "--out", str(tmp_path / "out")]
        )
